local opts = {
	ensure_installed = {
		"efm",
		"bashls",
		"tsserver",
		"solidity",
		"tailwindcss",
		"pyright",
		"html",
		"cssls",
		"lua_ls",
		"emmet_ls",
		"jsonls",
		"gopls",
		"ansiblels",
		"dockerls",
		"csharp_ls",
		"clangd",
		"cmake",
		"cssls",
		"codeqlls",
		"elp",
		"elixirls",
		"graphql",
		"html",
		"htmx",
		"golangci_lint",
		"jsonls",
		"kotlin_language_server",
		"autotools_language_server",
		"marksman",
		"powershell_es",
		"sdqlls",
		"terraformls",
		"vimls",
		"zls",
		"jdtls",
	},

	automatic_installation = true,
}

return {
	"williamboman/mason-lspconfig.nvim",
	opts = opts,
	event = "BufReadPre",
	dependencies = "williamboman/mason.nvim",
	lazy = false,
}
